import { Inter, Merriweather } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })
const merriweather = Merriweather({ weight: '400', subsets: ['latin'] })

export default function Component() {
  return (
    <div className={`min-h-screen bg-[#fff5e6] ${inter.className}`}>
      <header className="bg-[#8b0000] text-white py-4 sticky top-0 z-50">
        <div className="container mx-auto px-4">
          <h1 className={`text-2xl ${merriweather.className} font-bold`}>ShaadiToast</h1>
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-4 py-8">
        <section className="bg-white p-6 rounded-lg shadow-lg mb-8">
          <h1 className={`text-3xl font-bold text-[#8b0000] mb-6 ${merriweather.className}`}>
            Terms and Conditions
          </h1>
          <div className="space-y-4 text-[#333]">
            <p className="font-bold">Last Updated: 09/10/2024</p>
            
            <p>
              Please read these Terms of Service (the &quot;Terms&quot;) and our Privacy Policy carefully because they govern your use of the ShaadiToast website located at https://shaaditoast.com (the &quot;Site&quot;), ShaadiToast text generation services, and any text content generated by ShaadiToast services for you based on your User Content (defined below) (&quot;Generated Content&quot;). To make these Terms easier to read, the Site, our services, and the Generated Content are collectively called the &quot;Services.&quot;
            </p>

            <p className="font-bold">
              IMPORTANT NOTICE REGARDING ARBITRATION FOR U.S. CUSTOMERS: WHEN YOU AGREE TO THESE TERMS, YOU ARE AGREEING (WITH LIMITED EXCEPTION) TO RESOLVE ANY DISPUTE BETWEEN YOU AND SHAADITOAST THROUGH BINDING, INDIVIDUAL ARBITRATION RATHER THAN IN COURT. PLEASE REVIEW SECTION 16 &quot;DISPUTE RESOLUTION&quot; BELOW FOR DETAILS REGARDING ARBITRATION.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Agreement to Terms
            </h2>
            <p>
              By using our Services, you agree to be bound by these Terms. If you do not agree to be bound by these Terms, do not use the Services. If you are accessing and using the Services on behalf of a company (such as your employer) or other legal entity, you represent and warrant that you have the authority to bind that entity to these Terms. In that case, &quot;you&quot; and &quot;your&quot; will refer to that entity.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Privacy Policy
            </h2>
            <p>
              Please review our Privacy Policy, which also governs your use of the Services, for information on how we collect, use, and share your information, as well as for information on your privacy rights under the California Consumer Privacy Act (CCPA) if you are a California resident. The Privacy Policy is incorporated by reference into these Terms.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Changes to these Terms or the Services
            </h2>
            <p>
              We may update the Terms from time to time at our sole discretion. If we do, we&apos;ll notify you by posting the updated Terms on the Site and/or through other communications. It&apos;s important that you review the Terms whenever we update them or you use the Services. If you continue to use the Services after we have posted updated Terms, it means you accept and agree to the changes. If you do not agree to be bound by the changes, you may no longer use the Services. Because our Services are evolving over time, we may change or discontinue all or any part of the Services, at any time, and without notice, at our sole discretion.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Who May Use the Services?
            </h2>
            <p>
              You may use the Services only if you are 18 years or older and capable of forming a binding contract with ShaadiToast, and are not otherwise barred from using the Services under applicable law.
            </p>
            <p>
              For certain features of the Services, you will need an account. It is important that you provide us with accurate, complete, and current account information and keep this information up to date. If you fail to do so, we may suspend or terminate your account. To protect your account, keep your account details and password confidential, and notify us right away of any unauthorized use. You are responsible for all activities that occur under your account.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Feedback
            </h2>
            <p>
              We appreciate feedback, comments, ideas, proposals, and suggestions for improvements to the Services (&quot;Feedback&quot;). If you choose to submit Feedback, you agree that we are free to use it without any restriction or compensation to you.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Payments
            </h2>
            <p>
              ShaadiToast requires payment of a fee for use of the Services (or certain portions thereof), and you agree to pay such fees.
            </p>
            <p>
              <strong>General:</strong> When you purchase goods related to the Services (&quot;Goods&quot;), you expressly authorize us (or our third-party payment processor) to charge you for such Goods. We may ask you to supply additional information relevant to your purchase, including your credit card number, the expiration date of your credit card, and your email and postal addresses for billing and notification (such information, &quot;Payment Information&quot;). You represent and warrant that you have the legal right to use all payment methods represented by any such Payment Information. When you initiate a purchase, you authorize us to provide your Payment Information to third parties so we can complete the transaction and charge your payment method for the selected Goods (plus any applicable taxes and other charges). You may need to provide additional information to verify your identity before completing your purchase. By initiating a purchase, you agree to the pricing, payment, and billing policies applicable to such fees and charges, as posted or otherwise communicated to you. All payments for Goods are non-refundable and non-transferable except as expressly provided in these Terms and the Refund Policy. All fees and applicable taxes, if any, are payable in U.S. dollars.
            </p>
            <p>
              <strong>Refunds for Goods:</strong> You may receive a full refund of your purchase within seven (7) calendar days of your initial purchase. AFTER THAT, YOUR PURCHASE IS FINAL, AND YOU WILL NOT BE ABLE TO CANCEL OR RECEIVE A REFUND AT ANY TIME. However, if something unexpected happens during a transaction, we reserve the right to cancel your transaction for any reason; if we cancel, we will refund any payment you have made for that transaction. To request a refund, please email us at shaaditoast@greenpenailabs.com. Additional details are outlined in the Refund Policy.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Your Content
            </h2>
            <p>
              <strong>Posting Content:</strong> Our Services may allow you to store or share content such as text (in posts or communications with others), files, documents, graphics, images, music, software, audio, and video. Anything (other than Feedback) that you post or otherwise make available through the Services is referred to as &quot;User Content.&quot; ShaadiToast does not claim any ownership rights in User Content, and nothing in these Terms will be deemed to restrict any rights you may have to your User Content.
            </p>
            <p>
              <strong>Permissions to Your User Content:</strong> By making any User Content available through the Services, you hereby grant to ShaadiToast, its licensors, and their affiliates a non-exclusive, transferable, perpetual, irrevocable, worldwide, royalty-free, fully paid-up license, with the right to sublicense, to use, host, store, copy, communicate, modify, create derivative works based upon, distribute, publish, publicly display, and publicly perform your User Content in connection with ShaadiToast, its licensors, and their affiliates providing, operating, securing, and improving their services.
            </p>
            <p>
              <strong>Your Responsibility for User Content:</strong> You are solely responsible for all your User Content. You represent and warrant that you have (and will have) all rights necessary to grant us the license rights in your User Content under these Terms. You further represent and warrant that neither your User Content, nor your use and provision of your User Content to be made available through the Services, nor any use of your User Content by ShaadiToast on or through the Services, will infringe, misappropriate, or violate any third party&apos;s intellectual property rights, or rights of publicity or privacy, or result in the violation of any applicable law or regulation.
            </p>
            <p>
              <strong>Removal of User Content:</strong> You can remove your User Content by specifically deleting it. In certain instances, some of your User Content (such as posts or comments) may not be completely removed, and copies of your User Content may continue to exist on the Services. To the maximum extent permitted by law, we are not responsible or liable for the removal or deletion of (or the failure to remove or delete) any of your User Content.
            </p>
            <p>
              <strong>Your Use of Generated Content:</strong> Subject to your compliance with these Terms, ShaadiToast hereby grants you a non-exclusive, worldwide license, with the right to sublicense, to use, copy, modify, sell, create derivative works based upon, distribute, publicly display, and publicly perform Generated Content for your lawful business purposes.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Ownership of Intellectual Property
            </h2>
            <p>
              We may make available through the Services content that is subject to intellectual property rights, including Generated Content. We and our licensors (as applicable) retain all rights to that content.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Usage Requirements, General Prohibitions, and ShaadiToast Enforcement Rights
            </h2>
            <p>You agree that you will use the Services:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Only in a lawful manner and in compliance with all applicable laws;</li>
              <li>In accordance with the Terms, the license granted in Section 7(e), and any documentation, usage guidelines, parameters, and other requirements provided to you by ShaadiToast or its licensors, as may be modified from time to time;</li>
              <li>In a manner that does not infringe, misappropriate, or otherwise violate any of ShaadiToast&apos;s or its licensors&apos; rights or those of any other person or entity.</li>
            </ul>
            <p>You further agree not to:</p>
            <ul className="list-disc pl-6 space-y-2">
              <li>Post, upload, publish, or transmit any User Content that infringes or violates intellectual property rights, is false, defamatory, offensive, or promotes illegal activities;</li>
              <li>Distribute, sell, lend, or transfer any rights to the Services (except for Generated Content as permitted under this Agreement);</li>
              <li>Modify, alter, tamper with, or create derivative works of the Services, or attempt to do so;</li>
              <li>Use the Services with any malicious or harmful code or unauthorized software applications;</li>
              <li>Remove or alter any intellectual property rights notices appearing on or within the Services;</li>
              <li>Interfere with or disrupt the functionality or proper working of the Services;</li>
              <li>Use web scraping or web data extraction methods to extract data from the Services;</li>
              <li>Send unsolicited or unauthorized promotional materials;</li>
              <li>Forge or tamper with information in any email or use the Services to send deceptive or false information;</li>
              <li>Attempt to reverse-engineer, decompile, or discover the source code of the Services;</li>
              <li>Interfere with the access of any other user or network, including through spamming or overloading;</li>
              <li>Impersonate or misrepresent your affiliation with any person or entity.</li>
            </ul>
            <p>
              ShaadiToast is not obligated to monitor access to or use of the Services, but we reserve the right to do so and to remove any content that violates these Terms or applicable law.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              DMCA/Copyright Policy
            </h2>
            <p>
              ShaadiToast respects copyright law and expects its users to do the same. It is ShaadiToast&apos;s policy to terminate, in appropriate circumstances, account holders who repeatedly infringe or are believed to be repeatedly infringing the rights of copyright holders.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Links to Third-Party Websites or Resources
            </h2>
            <p>
              The Services may allow you to access third-party websites or other resources. We provide access only as a convenience and are not responsible for the content, products, or services available from those resources. You assume all risk arising from your use of any third-party resources.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Termination
            </h2>
            <p>
              We may suspend or terminate your access to and use of the Services, including suspending access to or terminating your account, at our sole discretion, at any time and without notice to you. You may request a refund by sending an email to shaaditoast@greenpenailabs.com. Upon any termination, discontinuation, or cancellation of the Services or your account, the following Sections will survive: 6(a), 6(b), 6(c) (only for payments due and owing to ShaadiToast prior to the termination), 6(d), 7(b), 7(c), 7(e), 7(f), 8, 9, 11, 12, 13, 14, 15, 16, and 17.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Warranty Disclaimers
            </h2>
            <p>
              THE SERVICES ARE PROVIDED &quot;AS IS,&quot; WITHOUT WARRANTY OF ANY KIND. WITHOUT LIMITING THE FOREGOING, WE AND OUR LICENSORS EXPLICITLY DISCLAIM ANY IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, QUIET ENJOYMENT, AND NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING OR USAGE OF TRADE. We and our licensors make no warranty that the Services will meet your requirements or be available on an uninterrupte d, secure, or error-free basis. We make no warranty regarding the quality, accuracy, timeliness, truthfulness, completeness, or reliability of any information or content on the Services.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Indemnity
            </h2>
            <p>
              You will indemnify and hold ShaadiToast, its licensors, their affiliates, and each of their officers, directors, employees, representatives, and agents harmless from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees arising out of or in any way connected with (a) your access to or use of the Services, (b) your User Content, (c) your violation of these Terms, or (d) your actual or alleged infringement, misappropriation, or violation of ShaadiToast, its licensors&apos;, or any third party&apos;s intellectual property or proprietary rights.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Limitation of Liability
            </h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER SHAADITOAST NOR ITS SERVICE PROVIDERS AND LICENSORS INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SERVICES WILL BE LIABLE FOR ANY INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES, OR DAMAGES FOR LOST PROFITS, LOST REVENUES, LOST SAVINGS, LOST BUSINESS OPPORTUNITY, LOSS OF DATA OR GOODWILL, SERVICE INTERRUPTION, COMPUTER DAMAGE OR SYSTEM FAILURE, OR THE COST OF SUBSTITUTE SERVICES OF ANY KIND ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES, WHETHER BASED ON WARRANTY, CONTRACT, TORT (INCLUDING NEGLIGENCE), PRODUCT LIABILITY, OR ANY OTHER LEGAL THEORY, AND WHETHER OR NOT SHAADITOAST OR ITS LICENSORS OR SERVICE PROVIDERS HAVE BEEN INFORMED OF THE POSSIBILITY OF SUCH DAMAGE, EVEN IF A LIMITED REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.
            </p>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY THE LAW OF THE APPLICABLE JURISDICTION, IN NO EVENT WILL SHAADITOAST&apos;S TOTAL LIABILITY ARISING OUT OF OR IN CONNECTION WITH THESE TERMS OR FROM THE USE OF OR INABILITY TO USE THE SERVICES EXCEED THE AMOUNTS YOU HAVE PAID OR ARE PAYABLE BY YOU TO SHAADITOAST FOR USE OF THE SERVICES OR ONE HUNDRED DOLLARS ($100), IF YOU HAVE NOT HAD ANY PAYMENT OBLIGATIONS TO SHAADITOAST, AS APPLICABLE.
            </p>
            <p>
              THE EXCLUSIONS AND LIMITATIONS OF DAMAGES SET FORTH ABOVE ARE FUNDAMENTAL ELEMENTS OF THE BASIS OF THE BARGAIN BETWEEN SHAADITOAST AND YOU.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Governing Law and Forum Choice
            </h2>
            <p>
              These Terms and any action related thereto will be governed by the Federal Arbitration Act, federal arbitration law, and the laws of the State of California, without regard to its conflict of laws provisions. Except as otherwise expressly set forth in Section 16 &quot;Dispute Resolution,&quot; the exclusive jurisdiction for all Disputes (defined below) that you and ShaadiToast are not required to arbitrate will be the state and federal courts located in Santa Clara County, and you and ShaadiToast each waive any objection to jurisdiction and venue in such courts.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Dispute Resolution
            </h2>
            <p>
              <strong>Mandatory Arbitration of Disputes.</strong> We each agree that any dispute, claim, or controversy arising out of or relating to these Terms or the breach, termination, enforcement, interpretation, or validity thereof, or the use of the Services (collectively, &quot;Disputes&quot;) will be resolved solely by binding, individual arbitration and not in a class, representative, or consolidated action or proceeding. You and ShaadiToast agree that the U.S. Federal Arbitration Act governs the interpretation and enforcement of these Terms, and that you and ShaadiToast are each waiving the right to a trial by jury or to participate in a class action. This arbitration provision shall survive termination of these Terms.
            </p>
            <p>
              <strong>Exceptions.</strong> As limited exceptions to Section 16(a) above: (i) we both may seek to resolve a Dispute in small claims court if it qualifies; and (ii) we each retain the right to seek injunctive or other equitable relief from a court to prevent (or enjoin) the infringement or misappropriation of our intellectual property rights.
            </p>
            <p>
              <strong>Conducting Arbitration and Arbitration Rules.</strong> The arbitration will be conducted by the American Arbitration Association (&quot;AAA&quot;) under its Consumer Arbitration Rules (the &quot;AAA Rules&quot;) then in effect, except as modified by these Terms. The AAA Rules are available at www.adr.org or by calling 1-800-778-7879. A party who wishes to start arbitration must submit a written Demand for Arbitration to AAA and give notice to the other party as specified in the AAA Rules. The AAA provides a form Demand for Arbitration at www.adr.org.
            </p>
            <p>
              Any arbitration hearings will take place in the county (or parish) where you live, unless we both agree to a different location. The parties agree that the arbitrator shall have exclusive authority to decide all issues relating to the interpretation, applicability, enforceability, and scope of this arbitration agreement.
            </p>
            <p>
              <strong>Arbitration Costs.</strong> Payment of all filing, administration, and arbitrator fees will be governed by the AAA Rules, and we won&apos;t seek to recover the administration and arbitrator fees we are responsible for paying unless the arbitrator finds your Dispute frivolous. If we prevail in arbitration, we&apos;ll pay all of our attorneys&apos; fees and costs and won&apos;t seek to recover them from you. If you prevail in arbitration, you will be entitled to an award of attorneys&apos; fees and expenses to the extent provided under applicable law.
            </p>
            <p>
              <strong>Injunctive and Declaratory Relief.</strong> Except as provided in Section 16(b) above, the arbitrator shall determine all issues of liability on the merits of any claim asserted by either party and may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party&apos;s individual claim. To the extent that you or we prevail on a claim and seek public injunctive relief (relief that prohibits unlawful acts threatening future injury to the public), the entitlement to and extent of such relief must be litigated in a civil court of competent jurisdiction and not in arbitration. Litigation of any issues of public injunctive relief shall be stayed pending the outcome of the merits of individual claims in arbitration.
            </p>
            <p>
              <strong>Class Action Waiver.</strong> YOU AND SHAADITOAST AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR ITS INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING. Further, if the parties&apos; Dispute is resolved through arbitration, the arbitrator may not consolidate another person&apos;s claims with your claims, and may not otherwise preside over any form of a representative or class proceeding. If this specific provision is found to be unenforceable, then the entirety of this Dispute Resolution section shall be null and void.
            </p>
            <p>
              <strong>Severability.</strong> With the exception of any of the provisions in Section 16(f) of these Terms (&quot;Class Action Waiver&quot;), if an arbitrator or court of competent jurisdiction decides that any part of these Terms is invalid or unenforceable, the other parts of these Terms will still apply.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              General Terms
            </h2>
            <p>
              <strong>Reservation of Rights.</strong> ShaadiToast and its licensors exclusively own all right, title, and interest in and to the Services, including all associated intellectual property rights. Notwithstanding the foregoing, ShaadiToast&apos;s licensor, OpenAI LLC, exclusively owns all right, title, and interest in and to Generated Content. ShaadiToast claims no ownership of Generated Content. You acknowledge that the Services are protected by copyright, trademark, and other laws of the United States and foreign countries. You agree not to remove, alter, or obscure any copyright, trademark, service mark, or other proprietary rights notices incorporated in or accompanying the Services.
            </p>
            <p>
              <strong>Entire Agreement.</strong> These Terms constitute the entire and exclusive understanding and agreement between ShaadiToast and you regarding the Services, and these Terms supersede and replace all prior oral or written understandings or agreements between ShaadiToast and you regarding the Services. If any provision of these Terms is held invalid or unenforceable by an arbitrator or a court of competent jurisdiction, that provision will be enforced to the maximum extent permissible, and the other provisions of these Terms will remain in full force and effect. You may not assign or transfer these Terms, by operation of law or otherwise, without ShaadiToast&apos;s prior written consent. Any attempt by you to assign or transfer these Terms, without such consent, will be null. ShaadiToast may freely assign or transfer these Terms without restriction. Subject to the foregoing, these Terms will bind and inure to the benefit of the parties, their successors, and permitted assigns.
            </p>
            <p>
              <strong>Notices.</strong> Any notices or other communications provided by ShaadiToast under these Terms will be given: (i) via email; or (ii) by posting to the Services. For notices made by email, the date of receipt will be deemed the date on which such notice is transmitted.
            </p>
            <p>
              <strong>Waiver of Rights.</strong> ShaadiToast&apos;s failure to enforce any right or provision of these Terms will not be considered a waiver of such right or provision. The waiver of any such right or provision will be effective only if in writing and signed by a duly authorized representative of ShaadiToast. Except as expressly set forth in these Terms, the exercise by either party of any of its remedies under these Terms will be without prejudice to its other remedies under these Terms or otherwise.
            </p>

            <h2 className={`text-xl font-bold text-[#8b0000] mt-4 ${merriweather.className}`}>
              Contact Information
            </h2>
            <p>
              If you have any questions about these Terms or the Services, please contact ShaadiToast at:
            </p>
            <p>
              ShaadiToast<br />
              2625 Middlefield Rd #435<br />
              Palo Alto, CA 94306<br />
              shaaditoast@greenpenailabs.com
            </p>
          </div>
        </section>
      </main>

      <footer className="bg-[#8b0000] text-white py-12">
        <div className="max-w-6xl mx-auto px-4">
          <div className="flex flex-col md:flex-row justify-between items-start mb-8">
            <div className="mb-8 md:mb-0 md:w-1/2">
              <h2 className={`text-2xl md:text-3xl font-bold mb-4 ${merriweather.className}`}>ShaadiToast</h2>
              <p className="text-sm max-w-md">
                We believe every wedding speech should be as unique and vibrant as the celebration itself. Our AI-powered assistant is here to help you craft words that resonate deeply with your loved ones, capturing the essence of Indian weddings while relieving you of the stress of speech writing.
              </p>
            </div>
            <div className="grid grid-cols-2 gap-8 text-sm">
              <div>
                <h3 className="font-semibold mb-2">Pages</h3>
                <ul className="space-y-2">
                  <li><a href="#" className="hover:text-[#ffd700] transition-colors duration-300">Craft Your Speech</a></li>
                  <li><a href="#" className="hover:text-[#ffd700] transition-colors duration-300">Refund Policy</a></li>
                  <li><a href="https://www.shaaditoast.com" className="hover:text-[#ffd700] transition-colors duration-300">FAQs</a></li>
                </ul>
              </div>
              <div>
                <h3 className="font-semibold mb-2">Legal</h3>
                <ul className="space-y-2">
                  <li><Link href="/terms-and-conditions" className="hover:text-[#ffd700] transition-colors duration-300">Terms</Link></li>
                  <li><a href="#" className="hover:text-[#ffd700] transition-colors duration-300">Privacy</a></li>
                  <li><a href="#" className="hover:text-[#ffd700] transition-colors duration-300">Contact</a></li>
                </ul>
              </div>
            </div>
          </div>
          <div className="border-t border-[#a50000] pt-8 text-sm text-center">
            <p>&copy; {new Date().getFullYear()} ShaadiToast. All rights reserved.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
